### ISSUE TITLE
404 once the container is running

### ISSUE THREAD

**Issue by daituzhang** [codemonauts/docker-craft-cms-dev-env#2]
Hi,
Thank you for the awesome project.
I followed the instruction to install the script.
But I'm getting 404 on localhost:8080.

I'm using craft 3, and I'm running the `craft start` in `my-project/craft/web` folder.
Once I shell into the container that's what I'm seeing
```
root@752b15490244:/local# ls
cpresources  index.php  mattie-michelle_190110_051619_itjgbwk2wc_v3.0.36.sql  src  uploads  web.config
```
Is the nginx hosting folder set to `/local/` ?
Is there a way to fix it?

Thank you

**Comment by fleaz** [comment]
Hi daituzhang,

according to your `ls` output I assume that you are to deep inside your project folder. You should run `craft start` directly in the toplevel of your project. 

If it's still not working just let me know. I'm happy to help :)

Best regards,
Felix

**Comment by daituzhang** [comment]
@fleaz 
Thank you for replying!
I did `craft start` one level upper and still get the same issue
```
root@93303836fefb:/local# ls
composer.json  composer.lock  config  craft  craft.bat  modules  storage  templates  vendor  web
```
based on craft3, the hosting folder is the `web` folder.
How the nginx hosting folder is set? Because I'm seeing `/www/html/` in the `/etc/nginx/sites-enabled/default` file.

Thank you,
Yulu

**Comment by fleaz** [comment]
Hi Yulu,

I talked with my colleague and we found the problem in your setup :)

First of all, the files in `/sited-enabled/` are not used, all the nginx configuration is stored in `/etc/nginx/nginx-7.x.conf`.

The problem with your setup is the fact that you used `web` for the hosting folder. Because of historical reasons, we use `public` for all our customers and therefore the nginx root folder also points to `/local/public`(Line 35 of the nginx config). The easiest way to fix this, is when you rename your folder from web to public. Craft doesn't care about this.

Best regards,
Felix
