### ISSUE TITLE
Unable to connect to the database

### ISSUE THREAD

**Issue by daituzhang** [codemonauts/docker-craft-cms-dev-env#3]
Hi,
I'm at the step to connect the craft to the database.
I've created a database using `craft create <db-name>`
and by looking into https://github.com/codemonauts/docker-craft-cms-dev-env/blob/master/bin/craft I  found the default root password is `root`
I'm able to connect to the database from my local mysql workbench

however when I try to connect to the database on craft installation page
using:
Driver: Mysql
Server:localhost
Port:3306
Username:root
Password:root
Database Name: mattie-michelle(the database I created)

I got error: `PDO exception: SQLSTATE[HY000] [2002] No such file or directory`
I think the server:localhost is not found?

I tried changing the server to:172.17.0.4
But got `PDO exception: SQLSTATE[HY000] [2002] Connection refused` error this time

Is there a way to fix it?

Thank you,
Yulu

**Comment by fleaz** [comment]
Hi Yulu,

the webserver and the database run in different containers, so using `localhost` won't work because it points to the webserver. The containers are linked together so you should be able to use `mysql` as your database server (and `cache` as your redis server in the same way). See L155 in `bin/craft`

**Comment by daituzhang** [comment]
That works. Thank you!
